# Generated by Django 5.0.7 on 2024-07-21 17:35

import adoptions.utils.sim_nao
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('genero', models.CharField(choices=[('Macho', 'MACHO'), ('Femêa', 'FEMEA')], max_length=6)),
                ('vacinado', models.CharField(choices=[('Sim', 'SIM'), ('Não', 'NAO')], max_length=4)),
                ('disponivel', models.CharField(choices=[('Sim', 'SIM'), ('Não', 'NAO')], default=adoptions.utils.sim_nao.CustomerChoice['SIM'], max_length=4)),
                ('cor', models.CharField(blank=True, max_length=125, null=True)),
                ('descricao', models.TextField()),
                ('mamando', models.CharField(choices=[('Sim', 'SIM'), ('Não', 'NAO')], max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoptions.type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnimalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='animal_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='adoptions.animal')),
            ],
        ),
    ]
