# Generated by Django 5.0.7 on 2024-07-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='raca',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
