# Generated by Django 5.0.7 on 2024-07-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0002_animal_raca'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='idade',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
