# Generated by Django 5.0.7 on 2024-08-06 11:55

import adoptions.utils.sim_nao
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0003_animal_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='castrado',
            field=models.CharField(choices=[('Sim', 'SIM'), ('Não', 'NAO')], default=adoptions.utils.sim_nao.CustomerChoice['NAO'], max_length=4),
        ),
    ]
